---
name: supply-chain

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

          #      - name: Set up Go
          #        uses: actions/setup-go@v2
          #        with:
          #          go-version: 1.19

          #      - name: Test
          #        run: go test ./...

      - name: Build Image
        id: build
        uses: garethjevans/build-action@main
        with:
          # auth
          server: ${{ secrets.SERVER }}
          token: ${{ secrets.TOKEN }}
          ca_cert: ${{ secrets.CA_CERT }}
          namespace: ${{ secrets.NAMESPACE }}
          # image config
          destination: gcr.io/rawlingsj/github-actions-poc
          context: .

      - name: Scan Image
        run:
          echo "${{ steps.build.outputs.name }}"
